#!/bin/bash
# Quick reference commands for Tienda Inglesa scraper

echo "🛒 URUGUAY SUPERMARKET SCRAPER - QUICK REFERENCE"
echo "=================================================="
echo ""

echo "📋 COMMON COMMANDS:"
echo ""

echo "1️⃣  Test the scraper (RECOMMENDED FIRST STEP)"
echo "   python test_tienda_inglesa_scraper.py"
echo "   ⏱️  Takes: 3-5 minutes"
echo "   ✅ Validates: Scraper is working correctly"
echo ""

echo "2️⃣  Scrape Tienda Inglesa (production)"
echo "   python production_scraper_runner.py"
echo "   ⏱️  Takes: 3-5 minutes"
echo "   📦 Output: 50-100 products"
echo ""

echo "3️⃣  Scrape all supermarkets"
echo "   # Edit production_scraper_runner.py first:"
echo "   # Set: SUPERMARKETS_TO_SCRAPE = ['Tienda Inglesa', 'Disco', 'Devoto']"
echo "   python production_scraper_runner.py"
echo "   ⏱️  Takes: 10-15 minutes"
echo "   📦 Output: 150-200 products"
echo ""

echo "4️⃣  Test with mock data (instant)"
echo "   python test_with_mock_data.py"
echo "   ⏱️  Takes: < 1 second"
echo "   ✅ Validates: Matching algorithm works"
echo ""

echo "5️⃣  Full POC test"
echo "   python run_poc.py"
echo "   ⏱️  Takes: 10-15 minutes"
echo "   📊 Output: Complete analysis with database"
echo ""

echo "📂 OUTPUT FILES:"
echo ""
echo "   data/"
echo "   ├── tienda_inglesa_production.json  # All products (JSON)"
echo "   ├── tienda_inglesa_production.csv   # All products (CSV)"
echo "   └── production.db                   # SQLite database"
echo ""
echo "   results/"
echo "   ├── production_matches.json         # Cross-store matches"
echo "   ├── production_price_comparison.csv # Price differences"
echo "   └── production_summary.json         # Statistics"
echo ""

echo "📚 DOCUMENTATION:"
echo ""
echo "   PROJECT_STATUS.md                   # Start here!"
echo "   TIENDA_INGLESA_SCRAPING_GUIDE.md   # Technical guide"
echo "   README.md                           # Project overview"
echo "   RESULTS_SUMMARY.md                  # POC results"
echo ""

echo "🔧 CONFIGURATION:"
echo ""
echo "   # In production_scraper_runner.py:"
echo "   HEADLESS = False              # Show browser (True for server)"
echo "   SUPERMARKETS_TO_SCRAPE = [...] # Which stores to scrape"
echo ""
echo "   # In tienda_inglesa_production_scraper.py:"
echo "   max_products = 100            # Product limit per run"
echo "   strategy = 'hybrid'           # 'search', 'category', or 'hybrid'"
echo ""

echo "🐛 TROUBLESHOOTING:"
echo ""
echo "   No products found?"
echo "   → Check internet connection"
echo "   → Verify Chrome is installed"
echo "   → Try with headless=False to see browser"
echo ""
echo "   Chrome/ChromeDriver error?"
echo "   → Update Chrome to latest version"
echo "   → ChromeDriver auto-downloads via webdriver-manager"
echo ""
echo "   Rate limited / blocked?"
echo "   → Increase delays in scraper"
echo "   → Run during off-peak hours (3-5 AM Uruguay)"
echo "   → Check if CAPTCHA appeared"
echo ""

echo "💡 TIPS:"
echo ""
echo "   • First time? Run test_tienda_inglesa_scraper.py"
echo "   • Debugging? Use headless=False to see browser"
echo "   • Production? Use headless=True and schedule at 3 AM"
echo "   • Need speed? Use strategy='search' (fastest)"
echo "   • Need coverage? Use strategy='hybrid' (recommended)"
echo ""

echo "✅ EXPECTED RESULTS:"
echo ""
echo "   Products scraped: 50-100 (Tienda Inglesa)"
echo "   Price coverage:   95%+"
echo "   Brand coverage:   80%+"
echo "   Image coverage:   98%+"
echo "   Scraping time:    3-5 minutes"
echo "   Success rate:     90-95%"
echo ""

echo "🎯 NEXT STEPS:"
echo ""
echo "   1. Run: python test_tienda_inglesa_scraper.py"
echo "   2. Review: data/test_hybrid_results.json"
echo "   3. Read: TIENDA_INGLESA_SCRAPING_GUIDE.md"
echo "   4. Scale: Add daily cron job"
echo ""

echo "=================================================="
echo "🚀 Ready to scrape! Start with the test command above."
